-- Document versions policies
CREATE POLICY "Users can view versions of documents they can access" ON document_versions FOR SELECT USING (organization_id IN (SELECT organization_id FROM profiles WHERE id = auth.uid()) AND EXISTS (SELECT 1 FROM documents WHERE documents.id = document_versions.document_id AND (uploaded_by = auth.uid() OR access_level IN ('public', 'internal') OR EXISTS (SELECT 1 FROM document_permissions WHERE document_id = documents.id AND target_user_id = auth.uid() AND can_view = true AND is_active = true))));

CREATE POLICY "Users can create versions for documents they can edit" ON document_versions FOR INSERT WITH CHECK (organization_id IN (SELECT organization_id FROM profiles WHERE id = auth.uid()) AND EXISTS (SELECT 1 FROM documents WHERE documents.id = document_versions.document_id AND (uploaded_by = auth.uid() OR EXISTS (SELECT 1 FROM document_permissions WHERE document_id = documents.id AND target_user_id = auth.uid() AND can_edit = true AND is_active = true))));

-- Document permissions policies
CREATE POLICY "Users can view permissions for documents they own or manage" ON document_permissions FOR SELECT USING (organization_id IN (SELECT organization_id FROM profiles WHERE id = auth.uid()) AND (target_user_id = auth.uid() OR EXISTS (SELECT 1 FROM documents WHERE documents.id = document_permissions.document_id AND uploaded_by = auth.uid()) OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('owner', 'manager', 'admin') AND organization_id = document_permissions.organization_id)));

CREATE POLICY "Document owners and managers can grant permissions" ON document_permissions FOR INSERT WITH CHECK (organization_id IN (SELECT organization_id FROM profiles WHERE id = auth.uid()) AND (EXISTS (SELECT 1 FROM documents WHERE documents.id = document_permissions.document_id AND uploaded_by = auth.uid()) OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('owner', 'manager', 'admin') AND organization_id = document_permissions.organization_id)));
