CREATE TABLE alteration_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL,
    order_id UUID NOT NULL,
    fitting_session_id UUID,
    customer_id UUID NOT NULL,
    request_number TEXT UNIQUE NOT NULL,
    request_date TIMESTAMPTZ DEFAULT NOW(),
    requested_by UUID,
    alteration_type TEXT NOT NULL,
    garment_areas JSONB NOT NULL,
    detailed_instructions TEXT NOT NULL,
    urgency TEXT DEFAULT 'normal',
    status TEXT DEFAULT 'pending',
    approval_status TEXT DEFAULT 'pending_approval',
    approved_by UUID,
    approved_at TIMESTAMPTZ,
    rejection_reason TEXT,
    assigned_to UUID,
    estimated_cost_aed NUMERIC(10,2),
    actual_cost_aed NUMERIC(10,2),
    charge_customer BOOLEAN DEFAULT false,
    customer_charge_aed NUMERIC(10,2),
    estimated_hours NUMERIC(4,1),
    actual_hours NUMERIC(4,1),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    quality_check_passed BOOLEAN,
    quality_checked_by UUID,
    quality_check_notes TEXT,
    customer_notified BOOLEAN DEFAULT false,
    customer_notification_sent_at TIMESTAMPTZ,
    notes TEXT,
    internal_notes TEXT,
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);