CREATE TABLE customers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID REFERENCES organizations(id) ON DELETE CASCADE,
    customer_code TEXT NOT NULL,
    full_name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    phone_secondary TEXT,
    emirates_id TEXT,
    visa_status TEXT,
    nationality TEXT,
    gender TEXT,
    date_of_birth DATE,
    anniversary_date DATE,
    profile_photo_url TEXT,
    address_line1 TEXT,
    address_line2 TEXT,
    city TEXT,
    emirate TEXT,
    postal_code TEXT,
    classification TEXT CHECK (classification IN ('VIP',
    'Regular',
    'New')) DEFAULT 'New',
    status TEXT CHECK (status IN ('Active',
    'Inactive',
    'Blocked')) DEFAULT 'Active',
    customer_since DATE DEFAULT CURRENT_DATE,
    last_order_date DATE,
    total_orders INTEGER DEFAULT 0,
    total_spent NUMERIC(10,2) DEFAULT 0,
    loyalty_points INTEGER DEFAULT 0,
    loyalty_tier TEXT CHECK (loyalty_tier IN ('Bronze',
    'Silver',
    'Gold',
    'Platinum')) DEFAULT 'Bronze',
    preferred_communication TEXT[],
    communication_opt_in BOOLEAN DEFAULT true,
    notes TEXT,
    tags TEXT[],
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(organization_id,
    customer_code)
);