CREATE TABLE designs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    design_code TEXT UNIQUE NOT NULL,
    design_name TEXT NOT NULL,
    garment_category TEXT NOT NULL,
    cultural_variant TEXT,
    description TEXT,
    technical_notes TEXT,
    fabric_requirements JSONB,
    base_price_aed NUMERIC(10,2) NOT NULL,
    markup_percentage NUMERIC(5,2) DEFAULT 0,
    final_price_aed NUMERIC(10,2) GENERATED ALWAYS AS (base_price_aed * (1 + markup_percentage / 100)) STORED,
    complexity_level TEXT,
    estimated_hours NUMERIC(5,1),
    season_tags TEXT[],
    occasion_tags TEXT[],
    style_tags TEXT[],
    popularity_score INTEGER DEFAULT 0,
    view_count INTEGER DEFAULT 0,
    selection_count INTEGER DEFAULT 0,
    is_featured BOOLEAN DEFAULT false,
    is_active BOOLEAN DEFAULT true,
    created_by UUID REFERENCES profiles(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);