CREATE TABLE employee_skills (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    employee_id UUID NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    skill_category TEXT NOT NULL,
    skill_name TEXT NOT NULL,
    skill_subcategory TEXT,
    proficiency_level TEXT NOT NULL,
    years_experience NUMERIC(3,1),
    verified_by UUID REFERENCES employees(id),
    verification_date DATE,
    verification_notes TEXT,
    last_assessment_date DATE,
    next_assessment_date DATE,
    quality_rating NUMERIC(3,2),
    speed_rating NUMERIC(3,2),
    consistency_rating NUMERIC(3,2),
    is_primary_skill BOOLEAN DEFAULT false,
    is_certified BOOLEAN DEFAULT false,
    certification_authority TEXT,
    certification_date DATE,
    certification_expiry_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);