CREATE TABLE employment_contracts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    employee_id UUID NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    contract_number TEXT UNIQUE NOT NULL,
    contract_type TEXT NOT NULL,
    contract_status TEXT DEFAULT 'active',
    start_date DATE NOT NULL,
    end_date DATE,
    renewal_date DATE,
    contract_language TEXT DEFAULT 'english',
    contract_file_url TEXT,
    contract_file_arabic_url TEXT,
    job_description TEXT NOT NULL,
    job_description_arabic TEXT,
    basic_salary_aed NUMERIC(10,2) NOT NULL,
    housing_allowance_aed NUMERIC(10,2) DEFAULT 0,
    transport_allowance_aed NUMERIC(10,2) DEFAULT 0,
    food_allowance_aed NUMERIC(10,2) DEFAULT 0,
    other_allowances_aed NUMERIC(10,2) DEFAULT 0,
    total_package_aed NUMERIC(10,2) GENERATED ALWAYS AS (basic_salary_aed + housing_allowance_aed + transport_allowance_aed + food_allowance_aed + other_allowances_aed) STORED,
    working_hours_weekly INTEGER DEFAULT 48,
    working_days_weekly INTEGER DEFAULT 6,
    annual_leave_days INTEGER DEFAULT 30,
    sick_leave_days INTEGER DEFAULT 90,
    notice_period_days INTEGER DEFAULT 30,
    probation_period_months INTEGER DEFAULT 3,
    end_of_service_benefit TEXT,
    medical_insurance BOOLEAN DEFAULT true,
    life_insurance BOOLEAN DEFAULT false,
    gratuity_calculation TEXT,
    termination_clause TEXT,
    non_compete_clause TEXT,
    confidentiality_clause TEXT,
    created_by UUID REFERENCES profiles(id),
    signed_by_employee_date DATE,
    signed_by_employer_date DATE,
    witness_name TEXT,
    witness_signature_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);