CREATE TABLE employee_certifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    employee_id UUID NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    certification_name TEXT NOT NULL,
    certification_name_arabic TEXT,
    issuing_authority TEXT NOT NULL,
    certification_number TEXT,
    issue_date DATE NOT NULL,
    expiry_date DATE,
    certification_level TEXT,
    certification_type TEXT,
    certification_category TEXT,
    certificate_file_url TEXT,
    verification_status TEXT DEFAULT 'pending',
    verified_by UUID REFERENCES employees(id),
    verification_date DATE,
    renewal_required BOOLEAN DEFAULT false,
    renewal_reminder_days INTEGER DEFAULT 30,
    cost_aed NUMERIC(8,2),
    training_hours INTEGER,
    cpe_credits NUMERIC(5,2),
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);