CREATE TABLE employees (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    employee_number TEXT UNIQUE NOT NULL,
    emirates_id TEXT UNIQUE,
    passport_number TEXT,
    passport_country TEXT,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    first_name_arabic TEXT,
    last_name_arabic TEXT,
    date_of_birth DATE,
    gender TEXT,
    nationality TEXT,
    religion TEXT,
    marital_status TEXT,
    email TEXT UNIQUE,
    phone_primary TEXT,
    phone_secondary TEXT,
    whatsapp_number TEXT,
    address_line1 TEXT,
    address_line2 TEXT,
    city TEXT,
    state TEXT,
    postal_code TEXT,
    country TEXT DEFAULT 'UAE',
    profile_photo_url TEXT,
    employment_status TEXT DEFAULT 'active',
    hire_date DATE NOT NULL,
    termination_date DATE,
    termination_reason TEXT,
    job_title TEXT NOT NULL,
    department_id UUID REFERENCES departments(id),
    manager_id UUID REFERENCES employees(id),
    employment_type TEXT,
    work_schedule TEXT,
    base_salary_aed NUMERIC(10,2),
    currency TEXT DEFAULT 'AED',
    pay_frequency TEXT,
    probation_period_months INTEGER DEFAULT 3,
    probation_end_date DATE,
    notice_period_days INTEGER DEFAULT 30,
    created_by UUID REFERENCES profiles(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);