CREATE TABLE employee_training (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    employee_id UUID NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    training_program_id UUID NOT NULL REFERENCES training_programs(id) ON DELETE CASCADE,
    enrollment_date DATE DEFAULT CURRENT_DATE,
    training_start_date DATE,
    training_end_date DATE,
    training_status TEXT DEFAULT 'enrolled',
    attendance_percentage NUMERIC(5,2),
    assessment_score NUMERIC(5,2),
    assessment_passed BOOLEAN,
    completion_date DATE,
    certificate_issued BOOLEAN DEFAULT false,
    certificate_number TEXT,
    certificate_url TEXT,
    cost_aed NUMERIC(8,2),
    approved_by UUID REFERENCES employees(id),
    approval_date DATE,
    feedback_rating NUMERIC(3,2),
    feedback_comments TEXT,
    trainer_feedback TEXT,
    skills_gained TEXT[],
    next_level_training_id UUID REFERENCES training_programs(id),
    reminder_sent BOOLEAN DEFAULT false,
    mandatory_completion_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);