CREATE TABLE fabric_library (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    fabric_code TEXT UNIQUE NOT NULL,
    fabric_name TEXT NOT NULL,
    fabric_type TEXT NOT NULL,
    fabric_weight_gsm INTEGER,
    fabric_composition TEXT,
    texture_finish TEXT,
    care_instructions TEXT,
    supplier_name TEXT,
    supplier_contact TEXT,
    cost_per_meter_aed NUMERIC(10,2) NOT NULL,
    selling_price_per_meter_aed NUMERIC(10,2) NOT NULL,
    stock_quantity_meters NUMERIC(8,2) DEFAULT 0,
    minimum_order_meters NUMERIC(5,2) DEFAULT 1,
    season_suitable TEXT[],
    garment_suitable TEXT[],
    country_of_origin TEXT,
    is_sustainable BOOLEAN DEFAULT false,
    is_available BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);