CREATE TABLE fitting_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL,
    customer_id UUID NOT NULL,
    order_id UUID,
    session_number INTEGER DEFAULT 1,
    session_type TEXT NOT NULL,
    scheduled_at TIMESTAMPTZ NOT NULL,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    status TEXT DEFAULT 'scheduled',
    conducted_by UUID,
    duration_minutes INTEGER,
    overall_fit_rating INTEGER CHECK (overall_fit_rating BETWEEN 1 AND 5),
    fit_assessment JSONB,
    requires_alterations BOOLEAN DEFAULT false,
    alterations_approved BOOLEAN DEFAULT false,
    customer_satisfaction INTEGER CHECK (customer_satisfaction BETWEEN 1 AND 5),
    next_session_recommended BOOLEAN DEFAULT false,
    next_session_date TIMESTAMPTZ,
    notes TEXT,
    internal_notes TEXT,
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);