CREATE TABLE orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID REFERENCES organizations(id) ON DELETE CASCADE,
    customer_id UUID REFERENCES customers(id) ON DELETE CASCADE,
    order_number TEXT NOT NULL,
    order_type TEXT CHECK (order_type IN ('bespoke',
    'casual',
    'alteration',
    'repair',
    'special_occasion')) NOT NULL,
    status TEXT CHECK (status IN ('new',
    'confirmed',
    'in_progress',
    'quality_check',
    'ready',
    'delivered',
    'cancelled')) DEFAULT 'new',
    sub_status TEXT,
    priority_level TEXT CHECK (priority_level IN ('rush',
    'normal',
    'low')) DEFAULT 'normal',
    garment_details JSONB DEFAULT '{}',
    design_notes TEXT,
    special_instructions TEXT,
    estimated_completion DATE,
    delivery_date DATE,
    total_amount NUMERIC(10,2) DEFAULT 0,
    advance_payment NUMERIC(10,2) DEFAULT 0,
    vat_amount NUMERIC(10,2) DEFAULT 0,
    final_amount NUMERIC(10,2) DEFAULT 0,
    assigned_to UUID REFERENCES profiles(id),
    progress_percentage INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    UNIQUE(organization_id,
    order_number)
);