CREATE TABLE performance_reviews (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    employee_id UUID NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    review_period_start DATE NOT NULL,
    review_period_end DATE NOT NULL,
    review_type TEXT NOT NULL,
    review_cycle TEXT,
    reviewer_id UUID NOT NULL REFERENCES employees(id),
    review_status TEXT DEFAULT 'pending',
    overall_rating NUMERIC(3,2),
    overall_rating_text TEXT,
    quality_rating NUMERIC(3,2),
    productivity_rating NUMERIC(3,2),
    reliability_rating NUMERIC(3,2),
    teamwork_rating NUMERIC(3,2),
    communication_rating NUMERIC(3,2),
    initiative_rating NUMERIC(3,2),
    leadership_rating NUMERIC(3,2),
    customer_service_rating NUMERIC(3,2),
    punctuality_rating NUMERIC(3,2),
    attendance_rating NUMERIC(3,2),
    strengths TEXT,
    areas_for_improvement TEXT,
    goals_achieved TEXT,
    goals_not_achieved TEXT,
    goals_next_period TEXT,
    development_plan TEXT,
    training_recommendations TEXT,
    career_aspirations TEXT,
    self_assessment_completed BOOLEAN DEFAULT false,
    self_assessment_date DATE,
    self_assessment_comments TEXT,
    peer_review_completed BOOLEAN DEFAULT false,
    peer_review_average_rating NUMERIC(3,2),
    manager_review_completed BOOLEAN DEFAULT false,
    manager_review_date DATE,
    manager_comments TEXT,
    hr_review_completed BOOLEAN DEFAULT false,
    hr_review_date DATE,
    hr_comments TEXT,
    employee_acknowledgment BOOLEAN DEFAULT false,
    employee_acknowledgment_date DATE,
    employee_signature_url TEXT,
    employee_comments TEXT,
    reviewer_signature_url TEXT,
    promotion_recommended BOOLEAN DEFAULT false,
    salary_increase_recommended BOOLEAN DEFAULT false,
    salary_increase_percentage NUMERIC(5,2),
    bonus_recommended BOOLEAN DEFAULT false,
    bonus_amount_aed NUMERIC(10,2),
    performance_improvement_plan BOOLEAN DEFAULT false,
    disciplinary_action BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);