CREATE TABLE training_programs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    program_code TEXT UNIQUE NOT NULL,
    program_name TEXT NOT NULL,
    program_name_arabic TEXT,
    description TEXT,
    program_category TEXT,
    training_type TEXT,
    skill_level TEXT,
    duration_hours INTEGER NOT NULL,
    duration_days INTEGER,
    max_participants INTEGER,
    min_participants INTEGER DEFAULT 1,
    cost_per_participant_aed NUMERIC(8,2),
    total_budget_aed NUMERIC(10,2),
    instructor_name TEXT,
    instructor_credentials TEXT,
    training_provider TEXT,
    training_location TEXT,
    training_format TEXT,
    certification_provided BOOLEAN DEFAULT false,
    certification_authority TEXT,
    certification_validity_months INTEGER,
    prerequisites TEXT,
    target_audience TEXT,
    learning_objectives TEXT[],
    training_materials TEXT[],
    assessment_method TEXT,
    passing_score NUMERIC(5,2),
    is_mandatory BOOLEAN DEFAULT false,
    is_active BOOLEAN DEFAULT true,
    approval_required BOOLEAN DEFAULT false,
    approved_by UUID REFERENCES employees(id),
    approval_date DATE,
    created_by UUID REFERENCES employees(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);