CREATE TABLE visa_tracking (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    employee_id UUID NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    visa_type TEXT NOT NULL,
    visa_number TEXT UNIQUE,
    passport_number TEXT NOT NULL,
    visa_status TEXT DEFAULT 'active',
    issue_date DATE NOT NULL,
    expiry_date DATE NOT NULL,
    entry_date DATE,
    sponsor_name TEXT,
    sponsor_license_number TEXT,
    visa_purpose TEXT,
    profession_on_visa TEXT,
    salary_on_visa_aed NUMERIC(10,2),
    entry_points TEXT[],
    exit_reentry_permit BOOLEAN DEFAULT false,
    emirates_id_number TEXT,
    emirates_id_expiry_date DATE,
    labor_card_number TEXT,
    labor_card_expiry_date DATE,
    medical_insurance_number TEXT,
    medical_insurance_expiry_date DATE,
    renewal_fee_aed NUMERIC(8,2),
    government_fees_aed NUMERIC(8,2),
    typing_center_fees_aed NUMERIC(8,2),
    total_renewal_cost_aed NUMERIC(8,2),
    renewal_reminder_days INTEGER DEFAULT 60,
    last_renewal_date DATE,
    next_renewal_due_date DATE,
    renewal_status TEXT DEFAULT 'not_due',
    authorized_signatory_id UUID REFERENCES employees(id),
    visa_file_url TEXT,
    emirates_id_copy_url TEXT,
    passport_copy_url TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);